### ISSUE TITLE
vue-pdf-app just doesn't work with upgraded Vuejs

### ISSUE THREAD

**Issue by krishnasism** [sandanat/vue-pdf-app#106]
Upgraded vuejs to version 2.7.10, and the module just stopped working with this error:
```
chunk-vendors.728920d1.js:92 TypeError: Cannot read properties of undefined (reading 'on')
    at ve (chunk-vendors.728920d1.js:92:5007)
    at Nr (chunk-vendors.728920d1.js:92:33224)
    at Object.insert (chunk-vendors.728920d1.js:92:36743)
    at M (chunk-vendors.728920d1.js:92:57140)
    at a.__patch__ (chunk-vendors.728920d1.js:92:58456)
    at Lr.e._update (chunk-vendors.728920d1.js:92:30904)
    at a.r (chunk-vendors.728920d1.js:92:31667)
    at e.get (chunk-vendors.728920d1.js:92:27886)
    at e.run (chunk-vendors.728920d1.js:92:28623)
    at Xr (chunk-vendors.728920d1.js:92:33863)
```

No change in the implementation of the module, just upgrading vuejs broke the module

Implementation 
`<vue-pdf-app style="height: 100vh;" :pdf="pdfdata" :config="config"></vue-pdf-app>`

Where **pdfdata** is ArrayBuffer type.

**Comment by krishnasism** [comment]
Better to just use iframe than this library 🤦🏻‍♂️
